### ISSUE TITLE
Seeing 500 issues related to SSL connection issues

### ISSUE THREAD

**Issue by cparedes** [chef/opscode-pushy-server#119]
System details:

- Ubuntu 14.04 LTS
- Chef Server 12
- Opscode Push Server 1.1.6-1

I've attempted to use `chef-server-ctl reconfigure` and `opscode-push-jobs-server reconfigure` with no change in behavior. I've restarted everything as well after attempting a reconfigure.

I've verified my erchef nginx certs using openssl s_client, and saw that it was valid with the CA certs already on my system.

I'm getting these errors every time I attempt to query the server with either `knife node status` or `knife job list`:

(client side)

```
knife job list
ERROR: Server returned error 500 for https://SERVER_URL/organizations/REDACTED/pushy/jobs, retrying 1/5 in 4s
ERROR: Server returned error 500 for https://SERVER_URL/organizations/REDACTED/pushy/jobs, retrying 2/5 in 6s
```

(server side)
```
2015-10-31 02:31:04.681 [error] <0.336.0> SSL: certify: ssl_handshake.erl:239:Fatal error: certificate unknown
2015-10-31 02:31:04.682 [error] <0.296.0> Webmachine error at path "/organizations/REDACTED/pushy/jobs" : {throw,{error,{conn_failed,{error,"certificate unknown"}}},[{pushy_http_common,fetch_authenticated,2,[{file,"src/pushy_http_common.erl"},{line,44}]},{pushy_org,fetch_org_id,1,[{file,"src/pushy_org.erl"},{line,38}]},{pushy_object,fetch_org_id,1,[{file,"src/pushy_object.erl"},{line,45}]},{pushy_wm_base,verify_request_signature,2,[{file,"src/pushy_wm_base.erl"},{line,157}]},{pushy_wm_base,is_authorized,2,[{file,"src/pushy_wm_base.erl"},{line,135}]},{webmachine_resource,resource_call,3,[{file,"..."},...]},...]}
```

Not sure what else I could be missing. I've checked https://tickets.opscode.com/browse/CHEF-5144 and seems it could be similar? Saw that the Erlang version bundled with opscode-push-jobs-server is R15B03.

**Comment by cparedes** [comment]
After chatting with support folks, I've tested 2.0.0~alpha.3 with erlang R16B03-1 and everything seems to work. The issue in R15B03 might have to do with the kind of SSL cert I'm passing in (wildcard cert, sha256 + RSA encryption)...

**Comment by e100** [comment]
I can confirm that 2.0.0~alpha.3 also resolved this problem for me.

**Comment by cparedes** [comment]
Just as a side note too, my hunch is that the reason why I saw the error in the first place was because one of the chain certificates was probably encoded in sha384 or sha512, which is not supported in R15B03. Might be worth checking if that's the case, if your server cert is sha256 but still exhibits the same behavior on the current stable version.

**Comment by e100** [comment]
In my case one of the chain certs is signed with sha384

**Comment by mengesb** [comment]
So I'm experiencing this same issue; could someone help with a solution? I'm using a comodo wildcard ssl cert and I think that I have the same problems as searches lead me back to here, and I'm not quite sure how I'd update the erlang processor in an embedded app setup like this. Instructions would be excellent.

**Comment by e100** [comment]
Go here: https://packagecloud.io/chef/current
Find push-jobs-server package version 2.0.0~alpha.3 or newer for your platform and install it.

You will also need to update your push-jobs-clients to 2.0

**Comment by mengesb** [comment]
My attempt at upgrading to `opscode-push-jobs-server-2.0.0~alpha.4+20160226080810` is resulting in HTTP 400 messages:

```
<push.client.public.ip> - - [28/Feb/2016:04:31:50 +0000]  "GET /organizations/<ORG>/pushy/config/<HOST> HTTP/1.1" 400 "0.001" 26 "-" "Chef Client/12.4.3 (ruby-2.1.6-p336; ohai-8.5.1; x86_64-linux; +http://opscode.com)" "<chef.server.local.ip>:10003" "400" "0.001" "12.4.3" "algorithm=sha1;version=1.0;" "<HOST>" "2016-02-28T04:31:54Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 1053
```

**Comment by mengesb** [comment]
haha; duh; one second; and thank you!

**Comment by mengesb** [comment]
OK now there are 404s:

```
==> /var/log/opscode/opscode-erchef/erchef.log <==
2016-02-28 04:44:17.302 [error] {<<"method=GET; path=/organizations/<ORG>/groups/pushy_job_readers; status=404; ">>,"Not Found"}

==> /var/log/opscode/opscode-erchef/crash.log <==
2016-02-28 04:44:17 =ERROR REPORT====
{<<"method=GET; path=/organizations/<ORG>/groups/pushy_job_readers; status=404; ">>,"Not Found"}

==> /var/log/opscode/opscode-erchef/current <==
2016-02-28_04:44:17.31472 [error] {<<"method=GET; path=/organizations/<ORG>/groups/pushy_job_readers; status=404; ">>,"Not Found"}

==> /var/log/opscode/opscode-erchef/requests.log.1 <==
2016-02-28T04:44:17Z erchef@127.0.0.1 method=GET; path=/organizations/<ORG>/principals/<USER>; status=200; req_id=g3IAA2QAEGVyY2hlZkAxMjcuMC4wLjEBAAHc6gAAAAAAAAAA; org_name=<ORG>; req_time=3; rdbms_time=0; rdbms_count=3; req_api_version=1; 
2016-02-28T04:44:17Z erchef@127.0.0.1 method=GET; path=/organizations/<ORG>/groups/pushy_job_readers; status=404; req_id=g3IAA2QAEGVyY2hlZkAxMjcuMC4wLjEBAAHdCgAAAAAAAAAA; org_name=mengesio; msg=group_not_found; couchdb_groups=false; couchdb_organizations=false; couchdb_containers=false; couchdb_acls=false; 503_mode=false; couchdb_associations=false; couchdb_association_requests=false; req_time=3; rdbms_time=0; rdbms_count=3; user=pivotal; req_api_version=1; 
```

I'll try re-running chef-client on the push-job-clients

**Comment by mengesb** [comment]
Looks like my client isn't able to successfully run:
```
2016-02-28_04:53:13.29198 INFO: [<HOST>] Starting client ...
2016-02-28_04:53:13.29203 INFO: [<HOST>] Retrieving configuration from https://chef-01.<DOMAIN>/organizations/<ORG>//pushy/config/<HOST>: ...
2016-02-28_04:53:13.29214 /opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb:209:in `rest': uninitialized constant Chef::REST (NameError)
2016-02-28_04:53:13.29216 	from /opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb:220:in `get_config'
2016-02-28_04:53:13.29217 	from /opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb:94:in `start'
2016-02-28_04:53:13.29217 	from /opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client/cli.rb:138:in `run_application'
2016-02-28_04:53:13.29218 	from /opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.0/lib/chef/application.rb:58:in `run'
2016-02-28_04:53:13.29218 	from /opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/bin/pushy-client:8:in `<top (required)>'
2016-02-28_04:53:13.29218 	from /opt/push-jobs-client/bin/pushy-client:53:in `load'
2016-02-28_04:53:13.29219 	from /opt/push-jobs-client/bin/pushy-client:53:in `<main>'
```

**Comment by mengesb** [comment]
OK so I finally fixed it. Seems there's a problem with the rest function usage/definition in `pushy_client.rb` at line 209.

Upgraded `opscode-push-jobs-server' to `2.0.0~alpha.4+20160226080810`
1. Installed chef_current packagecloud.io repository: `curl -s https://packagecloud.io/install/repositories/chef/current/script.rpm.sh | sudo bash`
2. Ensured it was disabled: `sudo sed -i "s/enabled=1/enabled=0/g" /etc/yum.repos.d/chef_current.repo`
3. Installed `2.0.0~alpha.4+20160226080810` version of `opscode-push-jobs-server`: `sudo yum --disablerepo=* --enablerepo=chef_current install -y opscode-push-jobs-server-2.0.0~alpha.4+20160226080810`
4. Run `opscode-push-jobs-server-ctl reconfigure`

Here's what I've done to get `push-jobs-cient` working at all clients:
1. Installed chef_current packagecloud.io repository: `curl -s https://packagecloud.io/install/repositories/chef/current/script.rpm.sh | sudo bash`
2. Ensured it was disabled: `sudo sed -i "s/enabled=1/enabled=0/g" /etc/yum.repos.d/chef_current.repo`
3. Installed `2.0.2+20160226200016-1.el6` version of push-jobs-client: `sudo yum --disablerepo=* --enablerepo=chef_current install -y push-jobs-client-2.0.2+20160226200016-1.el6`
4. Hacked `/opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb`
   ```
--- /a/opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb	2016-02-28 05:41:01.924003375 +0000
+++ /b/opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.0.2/lib/pushy_client.rb	2016-02-28 05:41:23.952003106 +0000
@@ -206,7 +206,10 @@
   private
 
   def rest
-    @rest ||= Chef::REST.new(chef_server_url, client_name, client_key)
+    @rest ||= begin
+      require 'chef/rest'
+      Chef::REST.new(chef_server_url, client_name, client_key)
+    end
   end
 
   def get_config
```
5. Restarted the client just to be safe.

**Comment by mengesb** [comment]
Submitted the PR on opscode-pushy-client

https://github.com/chef/opscode-pushy-client/pull/84

**Comment by charlesjohnson** [comment]
As there have been no updates to this issue in 162 days, and there have been new major releases of both the push-jobs server and client in the interim, I'm going to close this ticket as stale.

@mengesb  if this issue is still valid, please re-open, we'll be happy to assist further.
